CREATE TABLE USERS(
    USERNAME VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    PASSWORD VARCHAR(255),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES(
    USERNAME VARCHAR(255) NOT NULL,
    AUTHORITY VARCHAR(255),
    PRIMARY KEY (USERNAME)
);

CREATE TABLE WALLETS(
    CURRENCY VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    AMOUNT DOUBLE NOT NULL CHECK (AMOUNT >= 0),
    PRIMARY KEY (CURRENCY, USERNAME)
);
